### PR TITLE
Unlabeled alternates

### PR DESCRIPTION
**Pull request by joneshf**
Re: #12.

Adds the `At` alternates for most all of the functions. Doesn't add unlabeled alternates for `Run.Choose` as that has typeclass stuff going on.

Let me know if there's anything you'd like changed.

### CODE REVIEW

**Comment by joneshf** [comment]
Oh, I just realized there are no `At` alternates for aff/eff. Will add later today.

**Comment by joneshf** [comment]
cc @natefaubion

**Comment by natefaubion** [comment]
Thanks! This looks good.

**Comment by joneshf** [comment]
> Will add later today.

That turned out to be a lie :sweat_smile:.

While getting ready to add them, I realized there's `runBaseAff'` which requires two labels being chosen:

https://github.com/natefaubion/purescript-run/blob/425f13a88feb2337a91427e3a9af210a8222a846/src/Run.purs#L325


Didn't know what to do there, and then forgot to ping you about it. What do you think. Do you want unlabled aff/eff? If so, should `runBaseAffAt'` take two labels, or should there be no equivalent function?

**Comment by natefaubion** [comment]
I don't think it's necessary for Aff/Eff to be unlabelled because they are essentially primitive effects.

**Pull request merged**
